FROM golang:1.21.3-alpine3.18 as builder
WORKDIR /go/src/app
COPY . .
RUN go build 

FROM alpine:3.18
COPY --from=builder /go/src/app/TaipeiCityDashboardBE /app/
RUN apk --no-cache add postgresql-client
WORKDIR /app
EXPOSE 8080
CMD ["./TaipeiCityDashboardBE"]